import { DataTypes, Model } from 'sequelize';
import { sequelize } from '../config/database.js';


export class Questionario extends Model {}


Questionario.init({
id: { type: DataTypes.UUID, primaryKey: true, defaultValue: DataTypes.UUIDV4 },
userId: { type: DataTypes.UUID, allowNull: false },
empregado: DataTypes.BOOLEAN,
quantos_animais_possui: DataTypes.INTEGER,
motivos_para_adotar: DataTypes.STRING,
quem_vai_sustentar_o_animal: DataTypes.STRING,
numero_adultos_na_casa: DataTypes.INTEGER,
numero_criancas_na_casa: DataTypes.INTEGER,
idades_criancas: { type: DataTypes.JSON },
residencia_tipo: DataTypes.STRING,
proprietario_permite_animais: DataTypes.BOOLEAN,
todos_de_acordo_com_adocao: DataTypes.BOOLEAN,
responsavel_pelo_animal: DataTypes.STRING,
responsavel_concorda_com_adocao: DataTypes.BOOLEAN,
ha_alergico_ou_pessoas_que_nao_gostam: DataTypes.BOOLEAN,
gasto_mensal_estimado: DataTypes.FLOAT,
valor_disponivel_no_orcamento: DataTypes.BOOLEAN,
tipo_alimentacao: DataTypes.STRING,
local_que_o_animal_vai_ficar: DataTypes.STRING,
forma_de_permanencia: DataTypes.STRING,
forma_de_confinamento: DataTypes.STRING,
tera_brinquedos: DataTypes.BOOLEAN,
tera_abrigo: DataTypes.BOOLEAN,
tera_passeios_acompanhado: DataTypes.BOOLEAN,
tera_passeios_sozinho: DataTypes.BOOLEAN,
companhia_outro_animal: DataTypes.BOOLEAN,
companhia_humana_24h: DataTypes.BOOLEAN,
companhia_humana_parcial: DataTypes.BOOLEAN,
sem_companhia_humana: DataTypes.BOOLEAN,
sem_companhia_animal: DataTypes.BOOLEAN,
o_que_faz_em_viagem: DataTypes.STRING,
o_que_faz_se_fugir: DataTypes.STRING,
o_que_faz_se_nao_puder_criar: DataTypes.STRING,
animais_que_ja_criou: DataTypes.STRING,
destino_animais_anteriores: DataTypes.STRING,
costuma_esterilizar: DataTypes.BOOLEAN,
costuma_vacinar: DataTypes.BOOLEAN,
costuma_vermifugar: DataTypes.BOOLEAN,
veterinario_usual: DataTypes.STRING,
forma_de_educar: DataTypes.STRING,
envia_fotos_e_videos_do_local: DataTypes.BOOLEAN,
aceita_visitas_e_fotos_do_animal: DataTypes.BOOLEAN,
topa_entrar_grupo_adotantes: DataTypes.BOOLEAN,
concorda_com_taxa_adocao: DataTypes.BOOLEAN,
data_disponivel_para_buscar_animal: DataTypes.STRING,
}, {
sequelize,
modelName: 'Questionario',
tableName: 'questionarios',
timestamps: true,
});